# Copyright 2020 CYBERCRYPT
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Namespace
metadata:
  name: encryptonize
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: encryptonize-sa
  namespace: encryptonize
imagePullSecrets:
- name: gcr-json-key
---
apiVersion: v1
kind: Secret
metadata:
  name: encryptonize-config
  namespace: encryptonize
stringData:
  # Fill out the configuration below
  config.toml: |
    [keys]
    kek = "${KEK}"
    ask = "${ASK}"
    tek = "${TEK}"
    uek = "${UEK}"

    [authstorage]
    username = "root"
    host = "${AUTH_STORAGE_HOSTNAME}"
    port = "26257"
    database = "auth"
    sslmode = "verify-ca"
    sslrootcert = "data/ca.crt"
    sslcert = "data/client.root.crt"
    sslkey = "data/client.root.key"

    [objectstorage]
    url = "${OBJECT_STORAGE_HOSTNAME}"
    id = "${OBJECT_STORAGE_ID}"
    key = "${OBJECT_STORAGE_KEY}"
    cert = '''${OBJECT_STORAGE_CERT}'''

